flowchart

classDef version fill:#fff,stroke:#fff
VERSION["`VetData access flowchart,
version 0.2`"]
class VERSION version

classDef KUnode fill:#c5eff5,stroke:#197f8e
classDef KUimportant fill:#f5c9ca,stroke:#a31d20
classDef KUinfo fill:#8adeea,stroke:#197f8e,font-size:14pt

A["`Project needs
**VetStat** or **CHR** data`"]

VM{"`VetMyn project?`"}
class A,VM KUnode

A --> VM

subgraph VetMyn
direction TB
VM1["`Initial contact via mail:
VetData \*at* sund.ku.dk

Include the following:`"]
VM1a{{"`Hasteopgave reference number
or
VetMyn project number`"}}
VM1b{{"`short description of required CHR/VetStat data`"}}
VM1c{{"`full details of any other data sources used

incl. details of legal ownership of the data,
status of necessary contracts,
and plan for physically extracting the data
(e.g. via the goldfinger server for SEGES/L&F data)`"}}
VM1d{{"`full details of any anticipated requirements for technical support`"}}
end

class VetMyn KUimportant;
class VM1,VM1a,VM1b,VM1c,VM1d KUnode;

subgraph non-VetMyn
direction TB
nVM1["`Initial contact via mail:
VetData \*at* sund.ku.dk

Include the following:`"]
nVM1a{{"`details of the project:
funder
time period
anticipated legal basis for accessing the data`"}}
nVM1b{{"`description of the required data,
and anticipated plan for obtaining the data
(e.g. extract from CHR/VetStat database, or extraction of SEGES/L&F data via the goldfinger server`"}}
nVM1c{{"`full details of any anticipated requirements for technical support`"}}
end

class non-VetMyn KUimportant;
class nVM1,nVM1a,nVM1b,nVM1c KUnode;

VM --> VetMyn
VM1 ~~~ VM1a
VM1a ~~~ VM1b
VM1b ~~~ VM1c
VM1c ~~~ VM1d
VM --> non-VetMyn
nVM1 ~~~ nVM1a
nVM1a ~~~ nVM1b
nVM1b ~~~ nVM1c

B["`Preliminary consultation
(online or physical)`"]

VetMyn -- "may be requested" --> B
non-VetMyn -- "required" --> B

C["`Data specification approval`"]
D["`Legal approval`"]
E["`Data delivery
(goldfinger-encrypted Rdata by default)`"]

class B,C,D,E KUnode;

B --> C
C -. "if legal approval not relevant" .-> E
C -- "if relevant" --> D
D --> E

X["`More details can be found at XXX`"]
class X KUinfo
